import { Injectable } from '@nestjs/common';

export enum ENV_KEY {
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_DATABASE = 'DATABASE_DATABASE',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  SMTP_SERVER_USERNAME = 'SMTP_SERVER_USERNAME',
  SMTP_SERVER_PASSWORD = 'SMTP_SERVER_PASSWORD',
  SMTP_SERVER_EMAIL = 'SMTP_SERVER_EMAIL',

  JWT_SECRET = 'JWT_SECRET',
}

@Injectable()
export class EnvironmentService {
  get(key: ENV_KEY): string {
    return process.env[key];
  }
}
